sonarqube-check:
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    GIT_DEPTH: "0"  
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - echo $SONAR_PROPERTIES
    - echo -e $SONAR_PROPERTIES > sonar-project.properties
    - sonar-scanner || true
  allow_failure: true
  only:
    - shivam
    - kashif_dev
