
export const JSONData = {
  "முதல்-திருமுறை": [
    {
      "titleName": "01.081 நல்லார் தீமேவுந் தொழிலார்",
      "songLyrics": [
        {
          "id": 70316,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 1,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:05.464Z",
            "updatedAt": "2023-11-08T10:14:12.262Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 971,
            "rawSong": "*நல்லார் தீமேவுந் தொழிலார் நால்வேதஞ்\nசொல்லார் கேண்மையார் சுடர்பொற் கழலேத்த\nவில்லாற் புரஞ்செற்றான் மேவும் பதிபோலுங்\nகல்லார் மதில்சூழ்ந்த காழிந் நகர்தானே.1",
            "type": null,
            "searchRawSong": "\"*நல்லார்தீமேவுந்தொழிலார்நால்வேதஞ்\\nசொல்லார்கேண்மையார்சுடர்பொற்கழலேத்த\\nவில்லாற்புரஞ்செற்றான்மேவும்பதிபோலுங்\\nகல்லார்மதில்சூழ்ந்தகாழிந்நகர்தானே.1\"",
            "locale": "en"
          }
        },
        {
          "id": 70317,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 2,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:06.344Z",
            "updatedAt": "2023-11-08T10:14:12.557Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 972,
            "rawSong": "துளிவண் தேன்பாயும் இதழி தூமத்தந்\nதெளிவெண் டிங்கள்மா சுணநீர் திகழ்சென்னி\nஒளிவெண் டலைமாலை உகந்தா னூர்போலுங்\nகளிவண் டியாழ்செய்யுங் காழிந் நகர்தானே.",
            "type": null,
            "searchRawSong": "\"துளிவண்தேன்பாயும்இதழிதூமத்தந்\\nதெளிவெண்டிங்கள்மாசுணநீர்திகழ்சென்னி\\nஒளிவெண்டலைமாலைஉகந்தானூர்போலுங்\\nகளிவண்டியாழ்செய்யுங்காழிந்நகர்தானே.\"",
            "locale": "en"
          }
        },
        {
          "id": 70318,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 3,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:06.948Z",
            "updatedAt": "2023-11-08T10:14:12.882Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 973,
            "rawSong": "ஆலக் கோலத்தின் நஞ்சுண் டமுதத்தைச்\nசாலத் தேவர்க்கீந் தளித்தான் தன்மையால்\nபாலற் காய்நன்றும் பரிந்து பாதத்தால்\nகாலற் காய்ந்தானூர் காழிந் நகர்தானே.",
            "type": null,
            "searchRawSong": "\"ஆலக்கோலத்தின்நஞ்சுண்டமுதத்தைச்\\nசாலத்தேவர்க்கீந்தளித்தான்தன்மையால்\\nபாலற்காய்நன்றும்பரிந்துபாதத்தால்\\nகாலற்காய்ந்தானூர்காழிந்நகர்தானே.\"",
            "locale": "en"
          }
        },
        {
          "id": 70319,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 4,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:07.603Z",
            "updatedAt": "2023-11-08T10:14:13.176Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 974,
            "rawSong": "இப்பதிகத்தில் 4-ஆம் செய்யுள் மறைந்துபோயின.",
            "type": null,
            "searchRawSong": "\"இப்பதிகத்தில்4-ஆம்செய்யுள்மறைந்துபோயின.\"",
            "locale": "en"
          }
        },
        {
          "id": 70320,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 5,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:08.401Z",
            "updatedAt": "2023-11-08T10:14:13.456Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 975,
            "rawSong": "இப்பதிகத்தில் 5-ஆம் செய்யுள் மறைந்துபோயின.",
            "type": null,
            "searchRawSong": "\"இப்பதிகத்தில்5-ஆம்செய்யுள்மறைந்துபோயின.\"",
            "locale": "en"
          }
        },
        {
          "id": 70321,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 6,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:09.152Z",
            "updatedAt": "2023-11-08T10:14:13.718Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 976,
            "rawSong": "இப்பதிகத்தில் 6-ஆம் செய்யுள் மறைந்துபோயின.",
            "type": null,
            "searchRawSong": "\"இப்பதிகத்தில்6-ஆம்செய்யுள்மறைந்துபோயின.\"",
            "locale": "en"
          }
        },
        {
          "id": 70322,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 7,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:09.835Z",
            "updatedAt": "2023-11-08T10:14:13.997Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 977,
            "rawSong": "இப்பதிகத்தில் 7-ஆம் செய்யுள் மறைந்துபோயின.",
            "type": null,
            "searchRawSong": "\"இப்பதிகத்தில்7-ஆம்செய்யுள்மறைந்துபோயின.\"",
            "locale": "en"
          }
        },
        {
          "id": 70323,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 8,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:10.507Z",
            "updatedAt": "2023-11-08T10:14:14.286Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 978,
            "rawSong": "இரவில் திரிவோர்கட் கிறைதோ ளிணைபத்தும்\nநிரவிக் கரவாளை நேர்ந்தா னிடம்போலும்\nபரவித் திரிவோர்க்கும் பால்நீ றணிவோர்க்குங்\nகரவில் தடக்கையார் காழிந் நகர்தானே.",
            "type": null,
            "searchRawSong": "\"இரவில்திரிவோர்கட்கிறைதோளிணைபத்தும்\\nநிரவிக்கரவாளைநேர்ந்தானிடம்போலும்\\nபரவித்திரிவோர்க்கும்பால்நீறணிவோர்க்குங்\\nகரவில்தடக்கையார்காழிந்நகர்தானே.\"",
            "locale": "en"
          }
        },
        {
          "id": 70324,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 9,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:11.241Z",
            "updatedAt": "2023-11-08T10:14:14.559Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 979,
            "rawSong": "மாலும் பிரமனும் அறியா மாட்சியான்\nதோலும் புரிநூலுந் துதைந்த வரைமார்பன்\nஏலும் பதிபோலும் இரந்தோர்க் கெந்நாளுங்\nகாலம் பகராதார் காழிந் நகர்தானே.",
            "type": null,
            "searchRawSong": "\"மாலும்பிரமனும்அறியாமாட்சியான்\\nதோலும்புரிநூலுந்துதைந்தவரைமார்பன்\\nஏலும்பதிபோலும்இரந்தோர்க்கெந்நாளுங்\\nகாலம்பகராதார்காழிந்நகர்தானே.\"",
            "locale": "en"
          }
        },
        {
          "id": 70325,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 10,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:11.907Z",
            "updatedAt": "2023-11-08T10:14:14.824Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 980,
            "rawSong": "தங்கை யிடவுண்பார் தாழ்சீ வரத்தார்கள்\nபெங்கை யுணராதே பேணித் தொழுமின்கள்\nமங்கை யொருபாகம் மகிழ்ந்தான் மலர்ச்சென்னிக்\nகங்கை தரித்தானூர் காழிந் நகர்தானே.",
            "type": null,
            "searchRawSong": "\"தங்கையிடவுண்பார்தாழ்சீவரத்தார்கள்\\nபெங்கையுணராதேபேணித்தொழுமின்கள்\\nமங்கையொருபாகம்மகிழ்ந்தான்மலர்ச்சென்னிக்\\nகங்கைதரித்தானூர்காழிந்நகர்தானே.\"",
            "locale": "en"
          }
        },
        {
          "id": 70326,
          "attributes": {
            "titleNo": "81",
            "title": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "pann": "குறிஞ்சி",
            "audioUrl": "http://www.shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "thirumuraiId": 1119,
            "refId": 1119,
            "songNo": 11,
            "thalam": "சீர்காழி - 10-காழி",
            "country": "சோழநாடு காவிரி வடகரை",
            "author": "திருஞானசம்பந்தர்",
            "url": "https://shaivam.org/thirumurai/first-thirumurai/1119/thirugnanasambandar-devaram-seerkazhi-nallaar-thimevun",
            "centerNo": "14",
            "addon": "",
            "createdAt": "2023-11-08T04:22:12.622Z",
            "updatedAt": "2023-11-08T10:14:15.145Z",
            "publishedAt": "2023-11-08T08:19:30.000Z",
            "prevId": 981,
            "rawSong": "வாசம் கமழ்காழி மதிசெஞ் சடைவைத்த\nஈசன் நகர்தன்னை இணையில் சம்பந்தன்\nபேசுந் தமிழ்வல்லோர் பெருநீ ருலகத்துப்\nபாசந் தனையற்றுப் பழியில் புகழாரே.\n\nசுவாமி : பிரம்மபுரீஸ்வரர்; அம்பாள் : திருநிலைநாயகி.",
            "type": null,
            "searchRawSong": "\"வாசம்கமழ்காழிமதிசெஞ்சடைவைத்த\\nஈசன்நகர்தன்னைஇணையில்சம்பந்தன்\\nபேசுந்தமிழ்வல்லோர்பெருநீருலகத்துப்\\nபாசந்தனையற்றுப்பழியில்புகழாரே.\\n\\nசுவாமி:பிரம்மபுரீஸ்வரர்;அம்பாள்:திருநிலைநாயகி.\"",
            "locale": "en"
          }
        }
      ],
      "odhuvar": [
        {
          "id": 894,
          "attributes": {
            "Prefix": "tis-md-mthkumaran-",
            "Odhuvarname": "Madurai Muthukkumaran",
            "Pathigam": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "Pathikam_No": "81",
            "Odhuvar_Tamilname": "மதுரை முத்துக்குமரன்",
            "Audio_Url": "https://shaivam.org/gallery/audio/madurai-muthukkumaran/thirugnanasambandar-thirukkadaikkappu-muzhuvathum/tis-md-mthkumaran-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "createdAt": "2019-01-01T00:00:00.000Z",
            "updatedAt": "2023-01-21T16:04:44.585Z",
            "publishedAt": "2022-11-22T09:08:57.875Z",
            "locale": "en",
            "thirumariasiriyar": "திருஞானசம்பந்தர்  ",
            "sequence": 2
          }
        },
        {
          "id": 3732,
          "attributes": {
            "Prefix": "tis-sat-",
            "Odhuvarname": "Satgurunatha Odhuvar",
            "Pathigam": "01.081 நல்லார் தீமேவுந் தொழிலார்",
            "Pathikam_No": "81",
            "Odhuvar_Tamilname": "சற்குருநாத ஓதுவார்",
            "Audio_Url": "https://shaivam.org/gallery/audio/satguru/sam-thkkappu-muzhuvathum/tis-sat-sam-thkkappu-muzhu-part-2-368-1-81-nallaar-theemevum.mp3",
            "createdAt": "2019-01-01T00:00:00.000Z",
            "updatedAt": "2023-01-21T16:07:37.595Z",
            "publishedAt": "2022-11-22T09:08:57.875Z",
            "locale": "en",
            "thirumariasiriyar": "திருஞானசம்பந்தர்",
            "sequence": 1
          }
        }
      ]
    }
  ]
}