export const RouteTexts = {
    THIRIMURAI_LIST: 'ThrimuraiList',
    THIRIMURAI_HEADING: 'ThrimuraiHeadingPage',
    THRIMURAI_SONG: "ThrimuraiSong",
    SEARCH_SCREEN: 'SearchScreen',
    BOTTOM_TABS: 'BottomTabs',
    TEMPLE: 'Temple',
    TEMPLE_TABS_NAVIGATE: 'TempleTabsNavigate',
    CALENDER: 'Calender',
    FAVOURITE: 'Fav',
    MORE_OPTION: 'MoreOption',
    TEMPLE_Tabs: 'TempleTabs',
    HOME: 'Home',
    MY_TRIP: "MyTrip",
    ADD_TEMPLE: 'AddTemple',
    SONGS_LIST: 'SongsList',
    CREATE_TRIP: 'CreateTrip',
    TEMPLE_SELECTION: "TempleSelection",
    SPOTTING_ERROR_PAGE: "SpottingErrorPage",
    ERROR_SELECTION_PAGE: 'SelectErrorPage',
    ONBOARDING_SCREEN: 'Onboard',
    EVENT_DETAILS: 'EventDetails',
    VIRTUAL_EVENT_CREATE: 'CreateVirtualEvent',
    SUCCESS: 'Success'
}
